import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ui/Navbar";
import Footer from "./components/ui/Footer";
import AuthProvider from "./components/Providers/SessionProvider";
import { getServerSession } from "next-auth";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {


  
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1400px] mx-auto`}
        >

          <header>
            <nav className="">
              <Navbar />
            </nav>
          </header>

          <main className="min-h-[calc(100vh-242px)]">
            {children}
          </main>

          <footer>
            <Footer />
          </footer>

        </body>
      </AuthProvider>
    </html>
  );
}
